"""
Django settings for JessePiccione project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path
from google.cloud import secretmanager
CLIENT = secretmanager.SecretManagerServiceClient()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = CLIENT.access_secret_version(request={'name':'projects/piccione-dev/secrets/SECRET_KEY_VAR/versions/latest'}).payload.data.decode('utf-8')
OPENAI_API_KEY = CLIENT.access_secret_version(request={'name':'projects/piccione-dev/secrets/OPENAI_API_KEY/versions/latest'}).payload.data.decode('utf-8')

DBENGINE=CLIENT.access_secret_version(request={'name':'projects/piccione-dev/secrets/DATABASE_ENGINE/versions/latest'}).payload.data.decode('utf-8')
DBNAME=CLIENT.access_secret_version(request={'name':'projects/piccione-dev/secrets/DATABASE_NAME/versions/latest'}).payload.data.decode('utf-8')
DBHOST=CLIENT.access_secret_version(request={'name':'projects/piccione-dev/secrets/DATABASE_HOST/versions/latest'}).payload.data.decode('utf-8')
DBPORT=CLIENT.access_secret_version(request={'name':'projects/piccione-dev/secrets/DATABASE_PORT/versions/latest'}).payload.data.decode('utf-8')
DBUSER=CLIENT.access_secret_version(request={'name':'projects/piccione-dev/secrets/DATABASE_USERNAME/versions/latest'}).payload.data.decode('utf-8')
DBPASSWORD=CLIENT.access_secret_version(request={'name':'projects/piccione-dev/secrets/DATABASE_PASSWORD/versions/latest'}).payload.data.decode('utf-8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["*"]
CORS_ALLOWED_ORIGINS = [
                        'http://localhost:3000',
                        'http://localhost:8000',
                        'https://jessepiccione-info-backend.ue.r.appspot.com',
                        'https://www.jessepiccione.info',
                        'https://jessepiccione.info', 
                        'https://piccione.dev',
                        'https://portal.piccione.dev'
                        ]
CSRF_TRUSTED_ORIGINS = [
                        'http://localhost:3000',
                        'http://localhost:8000',
                        'https://jessepiccione-info-backend.ue.r.appspot.com',
                        'https://www.jessepiccione.info',
                        'https://jessepiccione.info', 
                        'https://piccione.dev',
                        'https://portal.piccione.dev'
                        ]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# HTTPS MODE
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False 
CSRF_COOKIE_SECURE = False
# Application definition
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'djoser',
    'JessePiccioneAssistant.apps.JessepiccioneassistantConfig',
    'Message.apps.MessageConfig',
    'Awards.apps.AwardsConfig',
    'Projects.apps.ProjectsConfig',
    'Skills.apps.SkillsConfig',
    'Education.apps.EducationConfig',
    'WorkExperience.apps.WorkexperienceConfig',
    'Resume.apps.ResumeConfig',
    'ResumeAPI.apps.ResumeapiConfig',
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]
ROOT_URLCONF = 'JessePiccione.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'JessePiccione.wsgi.application'
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': DBENGINE,
        'NAME': DBNAME,
        'HOST': DBHOST,
        'PORT': DBPORT, 
        'USER': DBUSER,
        'PASSWORD': DBPASSWORD,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_ROOT = 'static/'
STATIC_URL = '/static/'
STATICFILES_DIRS = [
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES":[
        'rest_framework.authentication.TokenAuthentication',  
    ]
}
CACHES = {
    "default":{
        "BACKEND":"django.core.cache.backends.db.DatabaseCache",
        "LOCATION":"backend_mysql_cache",
    }
}