# Generated by Django 5.0 on 2024-04-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contribution',
            field=models.CharField(max_length=512),
        ),
    ]
