options: 
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.ic/piccione-dev/portal:$BUILD_ID']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/piccione-dev/portal:$BUILD_ID']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'portal-piccione-dev', '--region', 'us-east1', --image, 'gcr.io/piccione-dev/website:$BUILD_ID']