options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_32
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/piccione-dev/portal:$BUILD_ID']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/piccione-dev/portal:$BUILD_ID']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - run
    - deploy
    - portal-piccione-dev
    - --region
    - us-east1
    - --image
    - gcr.io/piccione-dev/portal:$BUILD_ID
  secretEnv:
    - SECRET_KEY_VAR
    - OPENAI_API_KEY
    - DATABASE_ENGINE
    - DATABASE_HOST
    - DATABASE_NAME
    - DATABASE_PORT
    - DATABASE_USERNAME
    - DATABASE_PASSWORD
availableSecrets:
  secretManager:
    - versionName: 'projects/piccione-dev/secrets/SECRET_KEY_VAR/versions/latest'
      env: 'SECRET_KEY_VAR'
    - versionName: 'projects/piccione-dev/secrets/OPENAI_API_KEY/versions/latest'
      env: 'OPENAI_API_KEY'
    - versionName: 'projects/piccione-dev/secrets/DATABASE_ENGINE/versions/latest'
      env: 'DATABASE_ENGINE'
    - versionName: 'projects/piccione-dev/secrets/DATABASE_HOST/versions/latest'
      env: 'DATABASE_HOST'
    - versionName: 'projects/piccione-dev/secrets/DATABASE_NAME/versions/latest'
      env: 'DATABASE_NAME'
    - versionName: 'projects/piccione-dev/secrets/DATABASE_PORT/versions/latest'
      env: 'DATABASE_PORT'
    - versionName: 'projects/piccione-dev/secrets/DATABASE_USERNAME/versions/latest'
      env: 'DATABASE_USERNAME'
    - versionName: 'projects/piccione-dev/secrets/DATABASE_PASSWORD/versions/latest'
      env: 'DATABASE_PASSWORD'
