# Generated by Django 5.0.1 on 2024-02-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkExperience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='location',
            field=models.CharField(default='Remote', max_length=100),
            preserve_default=False,
        ),
    ]
