# Generated by Django 5.0 on 2024-03-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='rating',
        ),
    ]
