# Generated by Django 5.2.10 on 2026-01-26 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageentry',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 17, 56, 17, 872743)),
        ),
        migrations.AlterField(
            model_name='homepageentry',
            name='last_edit',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 17, 56, 17, 872743)),
        ),
    ]
