# Generated by Django 5.0 on 2024-03-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_technologies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technologies',
            new_name='Technology',
        ),
    ]
