# Generated by Django 5.0 on 2024-03-05 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_rename_technologies_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='pageEntry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Resume.homepageentry'),
            preserve_default=False,
        ),
    ]
