# Generated by Django 5.2.10 on 2026-01-27 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_alter_homepageentry_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageentry',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 19, 47, 21, 982851)),
        ),
        migrations.AlterField(
            model_name='homepageentry',
            name='last_edit',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 19, 47, 21, 982851)),
        ),
    ]
