# Generated by Django 5.2.10 on 2026-01-27 00:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0005_alter_homepageentry_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageentry',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='homepageentry',
            name='last_edit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
