# Generated by Django 5.1.2 on 2024-11-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Awards', '0002_awardcategory_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardcategory',
            name='issuer',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
