# Generated by Django 5.1.2 on 2024-11-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Awards", "0004_alter_awardcategory_issuer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awardcategory",
            name="issuer",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="awardcategory",
            name="year",
            field=models.IntegerField(default=2024, null=True),
        ),
    ]
