# Generated by Django 5.1.6 on 2025-03-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Awards", "0005_alter_awardcategory_issuer_alter_awardcategory_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awardcategory",
            name="issuer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="awardcategory",
            name="year",
            field=models.IntegerField(blank=True, default=2025, null=True),
        ),
    ]
